---
- hosts: 172.31.33.144
  become: yes
  tasks:
    - include_tasks: myFile.yml
    - name: create a folder
      file:
        path: /home/ubuntu/myfolder01
        state: directory
    - name: i want  to copy file
      copy:
        src: staticfile.txt
        dest: /home/ubuntu/staticfile.txt

    - name: install apache2
      apt:
        name: apache2
        state: present
    - name: copy dynamic  file
      template:
        src: index.j2
        dest: /var/www/html/index.html
