---
- hosts: all
  become: yes
  tasks:
    - name: i want to install web server
      apt:
        name: apache2
        state: present

    - name: tree here
      apt:
        name: tree
        state: present
