---
- name: download tomcat tar file
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.6/bin/apache-tomcat-10.0.6.tar.gz
    dest:
    force_basic_auth: yes

- name: create a folder
  file:
    path: /opt/tomcat
    state: directory

- name: extracting tar file
  command:
    cmd: sudo tar xzvf /home/ubuntu/apache-tomcat-10.0.6.tar.gz -C /opt/tomcat --strip-components=1
    creates: /opt/tomcat/LICENSE
